In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [7]:
df = sns.load_dataset("titanic")

In [8]:
df.head(10)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False

In [9]:
df.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [12]:
df.fillna({'age': df['age'].mean()},inplace=True)

In [19]:
df.dropna(subset=['embarked'],inplace=True)

In [20]:
df.isna().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         0
class            0
who              0
adult_male       0
deck           688
embark_town      0
alive            0
alone            0
dtype: int64

In [22]:
df['sex'] = df['sex'].map({'male':0,'female':1})

In [23]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,0,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,1,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,1,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,1,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,0,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [25]:
df = pd.get_dummies(df,columns=['embarked'])

In [26]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,class,who,adult_male,deck,embark_town,alive,alone,embarked_C,embarked_Q,embarked_S
0,0,3,0,22.0,1,0,7.2500,Third,man,True,NaN,Southampton,no,False,False,False,True
1,1,1,1,38.0,1,0,71.2833,First,woman,False,C,Cherbourg,yes,False,True,False,False
2,1,3,1,26.0,0,0,7.9250,Third,woman,False,NaN,Southampton,yes,True,False,False,True
3,1,1,1,35.0,1,0,53.1000,First,woman,False,C,Southampton,yes,False,False,False,True
4,0,3,0,35.0,0,0,8.0500,Third,man,True,NaN,Southampton,no,True,False,False,True

In [29]:
from sklearn.preprocessing import StandardScaler

In [30]:
ss = StandardScaler()

In [31]:
df[['age','fare','sex','pclass']] = ss.fit_transform(df[['age','fare','sex','pclass']])

In [32]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,class,who,adult_male,deck,embark_town,alive,alone,embarked_C,embarked_Q,embarked_S
0,0,0.825209,-0.735342,-0.590495,1,0,-0.500240,Third,man,True,NaN,Southampton,no,False,False,False,True
1,1,-1.572211,1.359911,0.643971,1,0,0.788947,First,woman,False,C,Cherbourg,yes,False,True,False,False
2,1,0.825209,1.359911,-0.281878,0,0,-0.486650,Third,woman,False,NaN,Southampton,yes,True,False,False,True
3,1,-1.572211,1.359911,0.412509,1,0,0.422861,First,woman,False,C,Southampton,yes,False,False,False,True
4,0,0.825209,-0.735342,0.412509,0,0,-0.484133,Third,man,True,NaN,Southampton,no,True,False,False,True

In [33]:
from sklearn.model_selection import train_test_split

In [35]:
X = df.drop(columns=['survived'])

In [37]:
y = df['survived']

In [38]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

In [42]:
X_train.shape,X_test.shape

((622, 16), (267, 16))